# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('user_iden', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=30, null=True)),
                ('l_name', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=30, null=True, unique=True)),
                ('phone', models.CharField(max_length=30, null=True, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
